### ISSUE TITLE
希望加入的功能

### ISSUE THREAD

**Issue by CaptainRuby** [shadeofgod/beijing-hell#1]
1.存钱取钱支持默认全部存放和全部取出
2.存钱取钱有“操作成功”的提示，并显示操作后的现金
3.cmd中加入显示排行榜命令
4.排行榜降序显示
Thanks♪(･ω･)ﾉ

**Comment by zoubingwu** [comment]
@CaptainRuby  已经全部加上了，可以试试

**Comment by CaptainRuby** [comment]
@shadeofgod 完美！
